default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      database: jaffle-sshop          # = project_id
      schema: analytics               # = dataset par défaut de tes modèles
      location: europe-west1
      threads: 16
      keyfile: "D:/dbt-project/05-10-2025-Keys/jaffle-sshop-b2db5c1c4ce5.json"
      # (ou) keyfile: "D:\\dbt-project\\05-10-2025-Keys\\jaffle-sshop-b2db5c1c4ce5.json"
      # dataproc_batch: null          # inutile, tu peux l’omettre

