name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'jaffleshop'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
